### ISSUE TITLE
Add to_dict method to model classes

### ISSUE THREAD

**Issue by declaresub** [heron-data/client-python#10]
I want to save heron transactions to a database in json format.  Thus it would be convenient if the various model classes had a to_dict or similarly-named method that returns a dict representation of a model object.  Preferably the dict returned could be passed to Model.__init__ to reconstitute the object.

**Comment by cesarferradas** [comment]
@declaresub thanks for the suggestion! You can always convert a python object into a dictionary by using `vars()`, so you could do that no problem. Because this is not always clear, I'm adding a `to_dict()` instance method for convenience in PR #11

**Comment by cesarferradas** [comment]
This method is now available in version 0.1.3: https://pypi.org/project/heron-data/0.1.3/

**Comment by declaresub** [comment]
Actually, you cannot always convert a python object into a dictionary using vars -- instances of a class created with a __slots__ attribute, in particular.  But the real problem with this implementation is that it doesn't fit the use case of serializing to JSON.  A Transaction object has a merchant attribute of type Optional[Merchant].  This to_dict method will not convert the Merchant object to a dict.
